#!/bin/bash
# Configurar usuario y contrasena de github
# Editando el archivo donde se almacenan estas credencials
cat > ~/.git-credentials
# @1: nombre de usuarios github
# @2: Token personal access
https://$1:$2@github.com
exit
