#!/bin/bash
# Estableciendo nombre de usuario y correo
git config --global user.name $1
git config --global user.email $1

# Elegir el editor para cuando git te solicite introducir un mensaje o arreglar conflictos
git config --global core.editor "vim"

# Guarde el nombre y correo en el almacenamiento de credenciales de git
git config --global credential.helper store

