#!/bin/bash
# Estableciendo nombre de usuario y correo
git config --global user.name "jordanbsandoval"
git config --global user.email "1608@holbertonschool.com"

# Elegir el editor para cuando git te solicite introducir un mensaje o arreglar conflictos
git config --global core.editor "vim"

# Guarde el nombre y correo en el almacenamiento de credenciales de git
git config --global credential.helper store

