version: '3.7'
services:
  mysqlDB1:
    image: "mysql:5.7.27"
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456789
      #- MYSQL_DATABASE=db_universidad
    container_name: mysql_DB

volumes:
  db-data:
